# Generated by Django 4.2.6 on 2023-12-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacaosensivel',
            name='telemovel',
            field=models.CharField(blank=True, default='987654321', max_length=20, null=True),
        ),
    ]
