# Generated by Django 4.2.6 on 2024-02-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0004_mentor_funcao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='funcao',
        ),
        migrations.AddField(
            model_name='mentor',
            name='grupo',
            field=models.ManyToManyField(blank=True, related_name='mentores', to='diario.grupo'),
        ),
    ]
