# Generated by Django 4.2.5 on 2024-02-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0005_remove_mentor_funcao_mentor_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='dadosCuidador',
            field=models.CharField(blank=True, choices=[('Cuidador', 'Cuidador'), ('Participante', 'Participante'), ('Familiar', 'Familiar')], default='Participante', max_length=20, null=True),
        ),
    ]
