# Generated by Django 4.2.6 on 2024-03-14 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0007_participante_testardoencas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participante',
            name='testarDoencas',
        ),
    ]
