# Generated by Django 4.2.6 on 2024-03-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0008_remove_participante_testardoencas'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuidador',
            name='beta_multipla',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='participante',
            name='beta_multipla',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
