# Generated by Django 4.2.6 on 2024-03-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0009_cuidador_beta_multipla_participante_beta_multipla'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuidador',
            name='comorbilidades',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='participante',
            name='comorbilidades',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
