# Generated by Django 4.2.6 on 2024-03-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0011_cuidador_escolhamultiplateste_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='escolhaMultiplaTeste',
            field=models.CharField(blank=True, choices=[('Alzheimer', 'Alzheimer'), ('Dor de cabeça aguda', 'Dor de cabeça aguda'), ('Dor de cabeça crónica', 'Dor de cabeça crónica'), ('Dor de cabeça recorrente', 'Dor de cabeça recorrente'), ('Dor de cabeça tensional', 'Dor de cabeça tensional'), ('Enxaqueca', 'Enxaqueca'), ('Epilepsia', 'Epilepsia'), ('Parkinson', 'Parkinson'), ('Outra', 'Outra')], default='Alzheimer', max_length=2000, null=True),
        ),
    ]
