# Generated by Django 4.2.6 on 2024-03-15 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0012_alter_participante_escolhamultiplateste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuidador',
            name='beta_multipla',
        ),
        migrations.RemoveField(
            model_name='participante',
            name='beta_multipla',
        ),
    ]
