# Generated by Django 4.2.6 on 2024-03-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0013_remove_cuidador_beta_multipla_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuidador',
            name='escolhaMultiplaTeste',
            field=models.CharField(blank=True, choices=[('Bipolar', 'Bipolar'), ('Demência', 'Demência'), ('Depressão Maior', 'Depressão Maior'), ('Doença Mental', 'Doença Mental'), ('Epilepsia', 'Epilepsia'), ('Esquizofrenia', 'Esquizofrenia'), ('Incapacidade Inteletual', 'Incapacidade Inteletual'), ('Nada (hiperatividade)', 'Nada (hiperatividade)'), ('Perturbação Bipolar', 'Perturbação Bipolar'), ('Não tem', 'Outra')], default='Alzheimer', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='participante',
            name='escolhaMultiplaTeste',
            field=models.CharField(blank=True, choices=[('Bipolar', 'Bipolar'), ('Demência', 'Demência'), ('Depressão Maior', 'Depressão Maior'), ('Doença Mental', 'Doença Mental'), ('Epilepsia', 'Epilepsia'), ('Esquizofrenia', 'Esquizofrenia'), ('Incapacidade Inteletual', 'Incapacidade Inteletual'), ('Nada (hiperatividade)', 'Nada (hiperatividade)'), ('Perturbação Bipolar', 'Perturbação Bipolar'), ('Não tem', 'Outra')], default='Alzheimer', max_length=2000, null=True),
        ),
    ]
