# Generated by Django 4.2.6 on 2023-12-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='doenca_cognitiva',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=10, null=True),
        ),
    ]
