# Generated by Django 4.2.6 on 2023-12-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo', '0003_risk_pre_diabetico_alter_risk_diabetes'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='recomendacoesAdicionais',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='risk',
            name='horas_jejum',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
