# Generated by Django 4.2.6 on 2023-12-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo', '0004_risk_recomendacoesadicionais_alter_risk_horas_jejum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk',
            name='recomendacoesAdicionais',
            field=models.CharField(blank=True, default='Pode continuar a sua vida normalmente, mas deve ter em atenção os seguintes pontos:', max_length=200),
        ),
    ]
