# Generated by Django 4.2.6 on 2023-12-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo', '0007_remove_risk_recomendacoesadicionais_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='comentario4',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
