# Generated by Django 4.2.6 on 2023-12-26 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo', '0008_risk_comentario4'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='risk',
            name='comentario4',
        ),
    ]
