# Generated by Django 4.2.6 on 2023-12-26 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo', '0009_remove_risk_comentario4'),
    ]

    operations = [
        migrations.RenameField(
            model_name='risk',
            old_name='recomendacoes_adicionais',
            new_name='recomendacoes',
        ),
    ]
