# Generated by Django 4.2.6 on 2023-12-26 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo', '0011_remove_risk_recomendacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='recomendacoes',
            field=models.TextField(blank=True),
        ),
    ]
