# Generated by Django 4.2.5 on 2024-02-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo', '0015_alter_risk_recomendacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='ifcc_teste',
            field=models.FloatField(default=0.0),
        ),
    ]
