# Generated by Django 4.2.5 on 2024-02-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo', '0016_risk_ifcc_teste'),
    ]

    operations = [
        migrations.RenameField(
            model_name='risk',
            old_name='ifcc_teste',
            new_name='eag_hba1',
        ),
        migrations.RemoveField(
            model_name='risk',
            name='eag',
        ),
        migrations.RemoveField(
            model_name='risk',
            name='ifcc',
        ),
        migrations.RemoveField(
            model_name='risk',
            name='ngsp',
        ),
        migrations.AddField(
            model_name='risk',
            name='ifcc_hba1',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='risk',
            name='ngsp_hba1',
            field=models.IntegerField(default=0),
        ),
    ]
