# Generated by Django 4.2.5 on 2024-02-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo', '0017_rename_ifcc_teste_risk_eag_hba1_remove_risk_eag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk',
            name='ngsp_hba1',
            field=models.FloatField(default=0),
        ),
    ]
