# Generated by Django 4.2.5 on 2024-02-26 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo', '0020_remove_risk_pergunta_cardiovascular'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='pergunta_cardiovascular',
            field=models.CharField(choices=[('Baixo', 'Sim'), ('Moderado', 'Moderado'), ('Alto', 'Alto'), ('Elevado', 'Elevado')], default='Baixo', max_length=10),
        ),
    ]
