# Generated by Django 4.2.5 on 2024-02-26 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo', '0021_risk_pergunta_cardiovascular'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='risk',
            name='pergunta_cardiovascular',
        ),
    ]
