# Generated by Django 4.2.6 on 2024-02-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo', '0022_remove_risk_pergunta_cardiovascular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk',
            name='pre_diabetico',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=10, null=True),
        ),
    ]
