# Generated by Django 4.2.6 on 2024-02-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo', '0023_alter_risk_pre_diabetico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk',
            name='pre_diabetico',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=10, null=True),
        ),
    ]
