# Generated by Django 4.2.6 on 2024-02-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo', '0024_alter_risk_pre_diabetico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk',
            name='pre_diabetico',
            field=models.BooleanField(default=False),
        ),
    ]
