# Generated by Django 4.2.6 on 2024-03-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo', '0026_risk_pergunta_cardiovascular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk',
            name='pergunta_cardiovascular',
            field=models.CharField(choices=[('Baixo', 'Baixo'), ('Moderado', 'Moderado'), ('Alto', 'Alto'), ('Elevado', 'Elevado'), ('Não se sabe', 'Não se sabe')], default='Não se sabe', max_length=100),
        ),
    ]
