# Generated by Django 4.2.6 on 2024-04-03 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo', '0029_remove_risk_pre_diabetico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk',
            name='doenca_cognitiva',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não'), ('Nao se sabe', 'Não se sabe')], default='Não se sabe', max_length=100),
        ),
    ]
