# Generated by Django 4.2.6 on 2024-04-03 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo', '0033_alter_risk_fumador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='pre_diabetico',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não'), ('Não se sabe', 'Não se sabe')], default='Não se sabe', max_length=100),
        ),
    ]
