# Generated by Django 4.2.6 on 2024-04-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo', '0034_risk_pre_diabetico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk',
            name='doenca_cognitiva',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='risk',
            name='pre_diabetico',
            field=models.BooleanField(default=False),
        ),
    ]
