# Generated by Django 4.2.6 on 2024-05-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo', '0035_alter_risk_doenca_cognitiva_alter_risk_pre_diabetico'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='pat_id_v2',
            field=models.CharField(blank=True, default=0, max_length=100),
        ),
    ]
