# Generated by Django 3.2.3 on 2022-05-07 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentha', '0002_auto_20220508_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='assunto',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='telefone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
