# Generated by Django 3.2.3 on 2022-05-11 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentha', '0003_auto_20220508_0048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40)),
                ('mensagem', models.TextField()),
                ('data', models.DateField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='contacto',
            name='distrito',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='referenciacao',
            field=models.CharField(blank=True, choices=[('ADEB', 'ADEB'), ('ASMAL', 'ASMAL'), ('Elo Social', 'Elo Social'), ('CVP', 'CVP'), ('FamiliarMente', 'FamiliarMente'), ('GIRA', 'GIRA')], max_length=30),
        ),
    ]
