# Generated by Django 4.1.1 on 2022-11-26 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentha', '0009_alter_noticia_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='titulo',
            field=models.CharField(max_length=120),
        ),
    ]
