# Generated by Django 4.0.5 on 2022-11-29 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0002_informacaosensivel_remove_auxiliar_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercicio',
            old_name='materiais',
            new_name='material',
        ),
        migrations.RemoveField(
            model_name='exercicio',
            name='fase',
        ),
        migrations.RemoveField(
            model_name='exercicio',
            name='sessoes',
        ),
        migrations.RemoveField(
            model_name='parte',
            name='numeroSessao',
        ),
        migrations.RemoveField(
            model_name='respostas',
            name='pergunta',
        ),
        migrations.AddField(
            model_name='exercicio',
            name='instrucao',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='exercicio',
            name='instrucao_participante',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='exercicio',
            name='ordem',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parte',
            name='exercicios',
            field=models.ManyToManyField(blank=True, to='diario.exercicio'),
        ),
        migrations.AddField(
            model_name='respostas',
            name='exercicio',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='diario.exercicio'),
        ),
        migrations.AddField(
            model_name='respostas',
            name='sessaoGrupo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='diario.sessaodogrupo'),
        ),
        migrations.AddField(
            model_name='sessao',
            name='programa',
            field=models.CharField(blank=True, choices=[('CARE', 'CARE'), ('COG', 'COG')], default='CARE', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='respostas',
            name='participante',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='diario.participante'),
        ),
    ]
