# Generated by Django 4.0.5 on 2022-11-29 17:48

import diario.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0004_rename_sessaogrupo_respostas_sessao_grupo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercicio',
            name='atividade',
        ),
        migrations.RemoveField(
            model_name='exercicio',
            name='objetivo',
        ),
        migrations.RemoveField(
            model_name='respostas',
            name='respostas',
        ),
        migrations.AddField(
            model_name='respostas',
            name='resposta_escrita',
            field=models.TextField(blank=True, default=None, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='respostas',
            name='resposta_submetida',
            field=models.ImageField(blank=True, null=True, upload_to=diario.models.submission_path),
        ),
        migrations.AlterField(
            model_name='escolha',
            name='resposta_escrita',
            field=models.CharField(blank=True, default=None, max_length=750, null=True),
        ),
    ]
