# Generated by Django 4.0.5 on 2022-11-29 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0005_remove_exercicio_atividade_remove_exercicio_objetivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupocare',
            name='nivelGDS',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='grupocare',
            name='programa',
            field=models.CharField(blank=True, choices=[('CARE', 'CARE'), ('COG', 'COG')], default='CARE', max_length=20, null=True),
        ),
    ]
